@echo off
setlocal
cd /d "%~dp0"
if exist ".venv\Scripts\python.exe" (set "PY=.venv\Scripts\python.exe") else (set "PY=python")
echo [1/24] Python compile smoke...
"%PY%" -m compileall -q client.py server.py server_directory.py common.py interior_art.py interior_layout.py map_viewer.py portable_map_runtime.py gameplay tools character_art.py character_catalog.py environment_art.py vehicle_art.py dev_tools\map_generator || goto :fail
echo [2/24] Imported runtime assets + movement settings...
"%PY%" tools\open_asset_audit.py || goto :fail
echo [3/24] Character sheet bounds + release-pack isolation audit...
"%PY%" tools\character_sheet_bounds_audit.py || goto :fail
echo [4/24] Dedicated 3x wide-gait animation audit...
"%PY%" tools\wide_gait_audit.py || goto :fail
echo [5/24] Current playable map validation...
"%PY%" tools\validate_mapfiles.py || goto :fail
echo [6/24] Building-to-road hard exclusion audit...
"%PY%" tools\building_road_audit.py || goto :fail
echo [7/24] Promoted-map scale / bicycle water and collision audit...
"%PY%" tools\map_scale_bicycle_audit.py || goto :fail
echo [8/24] Screenshot-reference generator isolation/schema audit...
"%PY%" tools\reference_map_pipeline_audit.py || goto :fail
echo [9/24] Spatial interest audit...
"%PY%" tools\spatial_interest_audit.py || goto :fail
echo [10/24] Global multiplayer world-map roster audit...
"%PY%" tools\multiplayer_map_roster_audit.py || goto :fail
echo [11/24] Multiplayer interiors / friends / local chat / player trading audit...
"%PY%" tools\multiplayer_interior_social_audit.py || goto :fail
echo [12/24] Vehicle passenger-seat audit...
"%PY%" tools\vehicle_passenger_audit.py || goto :fail
echo [13/24] Rotated vehicle-body collision / NPC run-over lifecycle audit...
"%PY%" tools\vehicle_body_runover_audit.py || goto :fail
echo [14/24] Deterministic traffic audit...
"%PY%" tools\deterministic_traffic_audit.py || goto :fail
echo [15/24] Unified multiplayer movement / pose replication audit...
"%PY%" tools\multiplayer_movement_audit.py || goto :fail
echo [16/24] Multi-level traversal / visible automatic jump / viewer parity audit...
"%PY%" tools\multilevel_map_audit.py || goto :fail
echo [17/24] OPEN NIGHT launcher integration audit...
"%PY%" tools\open_night_launcher_audit.py || goto :fail
echo [18/24] Public internet server auto-detection audit...
"%PY%" tools\public_server_discovery_audit.py || goto :fail
echo [19/24] Clean Pygbag web staging / Railway selection audit...
"%PY%" tools\web_build_audit.py || goto :fail
echo [20/24] Railway deployment batch control-flow audit...
"%PY%" tools\railway_batch_audit.py || goto :fail
echo [21/24] Portable .map / cache package audit...
"%PY%" tools\portable_map_audit.py || goto :fail
echo [22/24] Real server + portable-map playability smoke...
"%PY%" tools\pass38_playability_smoke.py || goto :fail
echo [23/24] In-game /bug capture + body-facing character audit...
"%PY%" tools\bug_feedback_audit.py || goto :fail
echo [24/24] Railway pending-report / explicit human-approval audit...
"%PY%" tools\bug_moderation_audit.py || goto :fail
echo.
echo LOCAL QA PASSED. Interactive checks: QUICK_LOCAL_TEST.bat, RUN_WEB_CLIENT.bat, Reference Map Trace Studio.
pause
exit /b 0
:fail
echo.
echo LOCAL QA FAILED. Review the error above.
pause
exit /b 1
