@echo off
setlocal
cd /d "%~dp0"
if exist ".venv\Scripts\python.exe" (set "PY=.venv\Scripts\python.exe") else (set "PY=python")
echo [1/28] Python compile smoke...
"%PY%" -m compileall -q client.py server.py server_directory.py versioning.py common.py interior_art.py interior_layout.py map_viewer.py portable_map_runtime.py gameplay tools character_art.py character_catalog.py environment_art.py vehicle_art.py dev_tools\map_generator || goto :fail
echo [2/28] Imported runtime assets + movement settings...
"%PY%" tools\open_asset_audit.py || goto :fail
echo [3/28] Character sheet bounds + release-pack isolation audit...
"%PY%" tools\character_sheet_bounds_audit.py || goto :fail
echo [4/28] Dedicated 3x wide-gait animation audit...
"%PY%" tools\wide_gait_audit.py || goto :fail
echo [5/28] Current playable map validation...
"%PY%" tools\validate_mapfiles.py || goto :fail
echo [6/28] Building-to-road hard exclusion audit...
"%PY%" tools\building_road_audit.py || goto :fail
echo [7/28] Map-scale / edge-tunnel / bicycle water and collision audit...
"%PY%" tools\map_scale_bicycle_audit.py || goto :fail
echo [8/28] Screenshot-reference generator isolation/schema audit...
"%PY%" tools\reference_map_pipeline_audit.py || goto :fail
echo [9/28] Spatial interest audit...
"%PY%" tools\spatial_interest_audit.py || goto :fail
echo [10/28] Global multiplayer world-map roster audit...
"%PY%" tools\multiplayer_map_roster_audit.py || goto :fail
echo [11/28] Multiplayer interiors / friends / SMS / local chat / player trading audit...
"%PY%" tools\multiplayer_interior_social_audit.py || goto :fail
echo [12/28] Vehicle passenger-seat audit...
"%PY%" tools\vehicle_passenger_audit.py || goto :fail
echo [13/28] Front-axle vehicle body / 30 mph NPC run-over lifecycle audit...
"%PY%" tools\vehicle_body_runover_audit.py || goto :fail
echo [14/28] Deterministic traffic audit...
"%PY%" tools\deterministic_traffic_audit.py || goto :fail
echo [15/28] Unified multiplayer movement / pose replication audit...
"%PY%" tools\multiplayer_movement_audit.py || goto :fail
echo [16/28] Multi-level traversal / visible automatic jump / viewer parity audit...
"%PY%" tools\multilevel_map_audit.py || goto :fail
echo [17/28] OPEN NIGHT launcher integration audit...
"%PY%" tools\open_night_launcher_audit.py || goto :fail
echo [18/28] Public internet server auto-detection audit...
"%PY%" tools\public_server_discovery_audit.py || goto :fail
echo [19/28] Clean Pygbag web staging / Railway selection audit...
"%PY%" tools\web_build_audit.py || goto :fail
echo [20/28] Railway deployment batch control-flow audit...
"%PY%" tools\railway_batch_audit.py || goto :fail
echo [21/28] Portable .map / cache package audit...
"%PY%" tools\portable_map_audit.py || goto :fail
echo [22/28] Real server + portable-map playability smoke...
"%PY%" tools\pass38_playability_smoke.py || goto :fail
echo [23/28] In-game /bug capture + body-facing character audit...
"%PY%" tools\bug_feedback_audit.py || goto :fail
echo [24/28] Railway pending-report / explicit human-approval audit...
"%PY%" tools\bug_moderation_audit.py || goto :fail
echo [25/28] Friend/SMS/version/water/updater reliability audit...
"%PY%" tools\v074_reliability_audit.py || goto :fail
echo [26/28] Clipboard and visible /bug reminder audit...
"%PY%" tools\v075_clipboard_chat_audit.py || goto :fail
echo [27/28] Pass 19 building-art convergence gate...
"%PY%" tools\building_art_convergence_audit.py --strict || goto :fail
echo [28/28] Pass 19 promoted map/package audit...
"%PY%" tools\pass19_map_audit.py || goto :fail
echo.
echo LOCAL QA PASSED. Interactive checks: QUICK_LOCAL_TEST.bat, RUN_WEB_CLIENT.bat, Reference Map Trace Studio.
pause
exit /b 0
:fail
echo.
echo LOCAL QA FAILED. Review the error above.
pause
exit /b 1
