@echo off
setlocal
cd /d "%~dp0"
if exist ".venv\Scripts\python.exe" (set "PY=.venv\Scripts\python.exe") else (set "PY=python")
echo [1/21] Python compile smoke...
"%PY%" -m compileall -q client.py server.py server_directory.py common.py interior_art.py interior_layout.py map_viewer.py portable_map_runtime.py gameplay tools character_art.py character_catalog.py environment_art.py vehicle_art.py dev_tools\map_generator || goto :fail
echo [2/21] Imported runtime assets + movement settings...
"%PY%" tools\open_asset_audit.py || goto :fail
echo [3/21] Character sheet bounds + release-pack isolation audit...
"%PY%" tools\character_sheet_bounds_audit.py || goto :fail
echo [4/21] Dedicated 3x wide-gait animation audit...
"%PY%" tools\wide_gait_audit.py || goto :fail
echo [5/21] Current playable map validation...
"%PY%" tools\validate_mapfiles.py || goto :fail
echo [6/21] Building-to-road hard exclusion audit...
"%PY%" tools\building_road_audit.py || goto :fail
echo [7/21] Map-scale / edge-tunnel / bicycle water and collision audit...
"%PY%" tools\map_scale_bicycle_audit.py || goto :fail
echo [8/21] Screenshot-reference generator isolation/schema audit...
"%PY%" tools\reference_map_pipeline_audit.py || goto :fail
echo [9/21] Spatial interest audit...
"%PY%" tools\spatial_interest_audit.py || goto :fail
echo [10/21] Global multiplayer world-map roster audit...
"%PY%" tools\multiplayer_map_roster_audit.py || goto :fail
echo [11/21] Multiplayer interiors / friends / local chat / player trading audit...
"%PY%" tools\multiplayer_interior_social_audit.py || goto :fail
echo [12/21] Vehicle passenger-seat audit...
"%PY%" tools\vehicle_passenger_audit.py || goto :fail
echo [13/21] Rotated vehicle-body collision / NPC run-over lifecycle audit...
"%PY%" tools\vehicle_body_runover_audit.py || goto :fail
echo [14/21] Deterministic traffic audit...
"%PY%" tools\deterministic_traffic_audit.py || goto :fail
echo [15/21] Multi-level traversal / visible automatic jump / viewer parity audit...
"%PY%" tools\multilevel_map_audit.py || goto :fail
echo [16/21] OPEN NIGHT launcher integration audit...
"%PY%" tools\open_night_launcher_audit.py || goto :fail
echo [17/21] Public internet server auto-detection audit...
"%PY%" tools\public_server_discovery_audit.py || goto :fail
echo [18/21] Clean Pygbag web staging / Railway selection audit...
"%PY%" tools\web_build_audit.py || goto :fail
echo [19/21] Railway deployment batch control-flow audit...
"%PY%" tools\railway_batch_audit.py || goto :fail
echo [20/21] Portable .map / cache package audit...
"%PY%" tools\portable_map_audit.py || goto :fail
echo [21/21] Real server + portable-map playability smoke...
"%PY%" tools\pass38_playability_smoke.py || goto :fail
echo.
echo LOCAL QA PASSED. Interactive checks: QUICK_LOCAL_TEST.bat, RUN_WEB_CLIENT.bat, Reference Map Trace Studio.
pause
exit /b 0
:fail
echo.
echo LOCAL QA FAILED. Review the error above.
pause
exit /b 1
